version: "3.9"
services:
  howler:
    build: .
    ports:
      - "80:80"
    links:
      - redis
  redis:
    image: redis
  cassandra:
    image: cassandra
    container_name: cassandra
    hostname: cassandra
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - "9042:9042"